apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongo
  template:
    metadata:
      labels:
        app: auth-mongo
    spec:
      containers:
        - name: auth-mongo
          image: 'bitnami/mongodb:4.4'
          env:
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: 127.0.0.1
            - name: MONGODB_REPLICA_SET_MODE
              value: primary
            - name: MONGODB_ROOT_USER
              value: root
            - name: MONGODB_ROOT_PASSWORD
              value: secret
            - name: MONGODB_REPLICA_SET_KEY
              value: replicasetkey123
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-svc
spec:
  selector:
    app: auth-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
